name: firestore_repository
description: firestore

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter packages
  cupertino_icons: ^1.0.0
  path_provider: 1.6.28
  image_picker: 0.6.7+22

  # Network
  http: ^0.12.1

  # firebase
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0
  meta: ^1.1.8


  # database
  shared_preferences: ^0.5.12+4
  uuid: ^2.2.2

  # packages
  authentication_repository:
    path: ../authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700